# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a dataset which contains information on World Cup matches. Let's use the Pandas commands learned in the previous lesson to learn more about our data!

## Objectives
You will be able to: 
- Use pandas methods and attributes to access information about a dataset 
- Index pandas dataframes with .loc, .iloc, and column names 
- Use a boolean mask to index pandas series and dataframes

## Load the data

Load the file `'WorldCupMatches.csv'` as a DataFrame in Pandas.

In [2]:
# Import pandas using the standard alias
import pandas as pd

# Import 'WorldCupMatches.csv' as a DataFrame
df = pd.read_csv("WorldCupMatches.csv")

## Common methods and attributes

Use the correct method to look at the first 7 rows of the dataset.

In [3]:
# Print the first 7 rows of df
df.head(7)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX
6,1930,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4,0,Bolivia,,18306.0,0,0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201,1092,YUG,BOL

Look at the last 3 rows of the data set.

In [4]:
# Print the last 3 rows of df
df.tail(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

Get a concise summary of the data using `.info()`.

In [5]:
# Print a concise summary of df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    int64
 1   Datetime              852 non-null    object
 2   Stage                 852 non-null    object
 3   Stadium               852 non-null    object
 4   City                  852 non-null    object
 5   Home Team Name        852 non-null    object
 6   Home Team Goals       852 non-null    int64
 7   Away Team Goals       852 non-null    int64
 8   Away Team Name        852 non-null    object
 9   Win conditions        852 non-null    object
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    int64
 12  Half-time Away Goals  852 non-null    int64
 13  Referee               852 non-null    object
 14  Assistant 1           852 non-null    object
 15  Assistant 2           852 non-null    object
 16  RoundID               852 non-null    int64
 17  MatchID               852 non-null    int64
 18  Home Team Initials    852 non-null    object
 19  Away Team Initials    852 non-null    object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.2+ KB

Obtain a tuple representing the number of rows and number of columns

In [12]:
# Print the number of rows and columns in df
df.shape

(852, 20)

Use the appropriate attribute to get the column names

In [13]:
# Print the column names of df
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting DataFrame information

When looking at the DataFrame's `.head()`, you might have noticed that the games are structured chronologically in the DataFrame.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [16]:
# Print rows 3 through 5
df.iloc[2:5]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

Now, print all the info from game 5-9, but we're only interested in printing out the, "Home Team Name" and the, "Away Team Name."

In [26]:
# Print rows 5 through 9 and columns 'Home Team Name' and 'Away Team Name'
df.iloc[5:10].loc[:,"Home Team Name":"Away Team Name":3]

  Home Team Name Away Team Name
5          Chile         Mexico
6     Yugoslavia        Bolivia
7            USA       Paraguay
8        Uruguay           Peru
9          Chile         France

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [27]:
# Print all info for games played in 1950 for Group 3
df.loc[df["Year"] == 1950]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
53,1950,24 Jun 1950 - 15:00,Group 1,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,4,0,Mexico,,81649.0,1,0,READER George (ENG),GRIFFITHS Benjamin (WAL),MITCHELL George (SCO),208,1187,BRA,MEX
54,1950,25 Jun 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,England,2,0,Chile,,29703.0,1,0,VAN DER MEER Karel (NED),GARDELLI Mario (BRA),DAHLNER Gunnar (SWE),208,1192,ENG,CHI
55,1950,25 Jun 1950 - 15:00,Group 2,Durival de Brito,Curitiba,Spain,3,1,USA,,9511.0,0,1,VIANA Mario (BRA),DA COSTA VIEIRA Jose (POR),DE LA SALLE Charles (FRA),208,1208,ESP,USA
56,1950,25 Jun 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Sweden,3,2,Italy,,36502.0,2,1,LUTZ Jean (SUI),BERANEK Alois (AUT),TEJADA Carlos (MEX),208,1219,SWE,ITA
57,1950,25 Jun 1950 - 15:00,Group 1,Independencia,Belo Horizonte,Yugoslavia,3,0,Switzerland,,7336.0,0,0,GALEATI Giovanni (ITA),EKLIND Ivan (SWE),DATTILO Generoso (ITA),208,1230,YUG,SUI
58,1950,28 Jun 1950 - 15:00,Group 1,Pacaembu,Sao Paulo,Brazil,2,2,Switzerland,,42032.0,2,1,AZON ROMA Ramon (ESP),BUSTAMANTE Sergio (CHI),DE NICOLA Cayetano (PAR),208,1188,BRA,SUI
59,1950,28 Jun 1950 - 15:00,Group 1,Eucaliptos,Porto Alegre,Yugoslavia,4,1,Mexico,,11078.0,2,0,LEAFE Reginald (ENG),DAHLNER Gunnar (SWE),VAN DER MEER Karel (NED),208,1225,YUG,MEX
60,1950,29 Jun 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Spain,2,0,Chile,,19790.0,2,0,MALCHER Alberto (BRA),MARINO Esteban (URU),ALVAREZ Alfredo (BOL),208,1193,ESP,CHI
61,1950,29 Jun 1950 - 15:30,Group 3,Durival de Brito,Curitiba,Sweden,2,2,Paraguay,,7903.0,2,1,MITCHELL Robert (SCO),LEMESIC Leo (YUG),GARCIA Prudencio (USA),208,1228,SWE,PAR
62,1950,29 Jun 1950 - 15:00,Group 2,Independencia,Belo Horizonte,USA,1,0,England,,10151.0,1,0,DATTILO Generoso (ITA),DE LA SALLE Charles (FRA),GALEATI Giovanni (ITA),208,1202,USA,ENG
63,1950,01 Jul 1950 - 15:00,Group 1,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,2,0,Yugoslavia,,142429.0,1,0,GRIFFITHS Benjamin (WAL),BERANEK Alois (AUT),DA COSTA VIEIRA Jose (POR),208,1191,BRA,YUG
64,1950,02 Jul 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Spain,1,0,England,,74462.0,0,0,GALEATI Giovanni (ITA),LUTZ Jean (SUI),DATTILO Generoso (ITA),208,1199,ESP,ENG
65,1950,02 Jul 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Italy,2,0,Paraguay,,25811.0,1,0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),208,1218,ITA,PAR
66,1950,02 Jul 1950 - 15:00,Group 4,Independencia,Belo Horizonte,Uruguay,8,0,Bolivia,,5284.0,4,0,READER George (ENG),VIANA Mario (BRA),LEMESIC Leo (YUG),208,1185,URU,BOL
67,1950,02 Jul 1950 - 15:40,Group 1,Eucaliptos,Porto Alegre,Switzerland,2,1,Mexico,,3580.0,2,0,EKLIND Ivan (SWE),DAHLNER Gunnar (SWE),BUSTAMANTE Sergio (CHI),208,1222,SUI,MEX
68,1950,02 Jul 1950 - 15:00,Group 2,Ilha do Retiro,Recife,Chile,5,2,USA,,8501.0,2,0,GARDELLI Mario (BRA),HEYEN Mario Ruben (PAR),ALVAREZ Alfredo (BOL),208,1194,CHI,USA
69,1950,09 Jul 1950 - 15:00,Group 6,Pacaembu,Sao Paulo,Uruguay,2,2,Spain,,44802.0,1,2,GRIFFITHS Benjamin (WAL),DATTILO Generoso (ITA),ALVAREZ Alfredo (BOL),209,1207,URU,ESP
70,1950,09 Jul 1950 - 15:00,Group 6,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,7,1,Sweden,,138886.0,3,0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),209,1189,BRA,SWE
71,1950,13 Jul 1950 - 15:00,Group 6,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,6,1,Spain,,152772.0,3,0,LEAFE Reginald (ENG),MITCHELL George (SCO),DA COSTA VIEIRA Jose (POR),209,1186,BRA,ESP
72,1950,13 Jul 1950 - 15:00,Group 6,Pacaembu,Sao Paulo,Uruguay,3,2,Sweden,,7987.0,1,2,GALEATI Giovanni (ITA),BERANEK Alois (AUT),DE NICOLA Cayetano (PAR),209,1231,URU,SWE
73,1950,16 Jul 1950 - 15:00,Group 6,Pacaembu,Sao Paulo,Sweden,3,1,Spain,,11227.0,2,0,VAN DER MEER Karel (NED),LUTZ Jean (SUI),GARCIA Prudencio (USA),209,1206,SWE,ESP
74,1950,16 Jul 1950 - 15:00,Group 6,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Uruguay,2,1,Brazil,,173850.0,0,0,READER George (ENG),ELLIS Arthur (ENG),MITCHELL George (SCO),209,1190,URU,BRA

Let's repeat the command above, but now we only want to print out the attendance column for the Group 3 games.

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [32]:
# Print the 'Attendance' column for games played in 1950 for Group 3
df[(df["Year"] == 1950) & (df["Stage"] == "Group 3")]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
56,1950,25 Jun 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Sweden,3,2,Italy,,36502.0,2,1,LUTZ Jean (SUI),BERANEK Alois (AUT),TEJADA Carlos (MEX),208,1219,SWE,ITA
61,1950,29 Jun 1950 - 15:30,Group 3,Durival de Brito,Curitiba,Sweden,2,2,Paraguay,,7903.0,2,1,MITCHELL Robert (SCO),LEMESIC Leo (YUG),GARCIA Prudencio (USA),208,1228,SWE,PAR
65,1950,02 Jul 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Italy,2,0,Paraguay,,25811.0,1,0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),208,1218,ITA,PAR

Throughout the entire history of the World Cup, how many home games were played by the Netherlands?

In [33]:
# Number of home games played by the Netherlands
len(df[df["Home Team Name"] == "Netherlands"])

32

How many games were played by the Netherlands in total?

In [35]:
# Number of games played by the Netherlands in total
len(df[(df["Home Team Name"] == "Netherlands") | (df["Away Team Name"] == "Netherlands")])

54

Next, let's try and figure out how many games the USA played in the 2014 World Cup.

In [42]:
# Number of games the USA played in the 2014 world cup
len(df[(df["Year"] == 2014) & 
       ((df["Home Team Name"] == "USA") | (df["Away Team Name"] == "USA"))])

5

Now, let's try to find out how many countries participated in the 1986 World Cup.

Hint 1: as a first step, create a new dataset that only contains games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [43]:
# Number of countries participated in the 1986 world cup
homecountries = df[df["Year"] == 1986]["Home Team Name"].unique()
awaycountries = df[df["Year"] == 1986]["Home Team Name"].unique()

uniquecontries = set(homecountries + awaycountries)
print(len(uniquecontries))

24

In World Cup history, how many matches had 5 goals or more in total?

In [45]:
# Number of matches that had 5 or more goals in total
df["Total Goals"] = df["Home Team Goals"] + df["Away Team Goals"]
len(df[df["Total Goals"] >= 5])

147

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column, "Half-time Goals."

In [47]:
# Create a new column 'Half-time Goals' in df
df["Half-time Goals"] = df["Half-time Home Goals"] + df["Half-time Away Goals"]

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [48]:
# Print all records containing the string 'Korea'
df.loc[df['Home Team Name'].str.contains('Korea'), 'Home Team Name']

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

Imagine that, for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [53]:
# Update the 'Home Team Name' and 'Home Team Initials' columns 
df.loc[df['Home Team Name'] == 'Korea DPR', 'Home Team Name'] = 'Korea'
df.loc[df['Home Team Name'] == 'Korea Republic', 'Home Team Name'] = 'Korea'
df.loc[df['Away Team Name'] == 'Korea DPR', 'Away Team Name'] = 'Korea'
df.loc[df['Away Team Name'] == 'Korea Republic', 'Away Team Name'] = 'Korea'
df.loc[df['Home Team Initials'] == 'KOR', 'Home Team Initials'] = 'NSK'
df.loc[df['Home Team Initials'] == 'KOR', 'Home Team Initials'] = 'NSK'
df.loc[df['Away Team Initials'] == 'PRK', 'Away Team Initials'] = 'NSK'
df.loc[df['Away Team Initials'] == 'PRK', 'Away Team Initials'] = 'NSK'

Make sure to verify your answer!

In [54]:
# Check the updated columns
df.loc[df['Away Team Name'].str.contains('Korea')]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Total Goals,Half-time Goals
80,1954,17 Jun 1954 - 18:00,Group 2,Hardturm,Zurich,Hungary,9,0,Korea,,...,0,VINCENTI Raymond (FRA),VON GUNTER Albert (SUI),STEINER Carl (AUT),211,1294,HUN,KOR,9,4
88,1954,20 Jun 1954 - 17:00,Group 2,Charmilles,Geneva,Turkey,7,0,Korea,,...,0,MARINO Esteban (URU),ORLANDINI Vincenzo (ITA),SCHONHOLZER Ernest (SUI),211,1304,TUR,KOR,7,4
171,1966,12 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Soviet Union,3,0,Korea,,...,0,GARDEAZABAL Juan (ESP),KANDIL Aly Hussein (EGY),DIENST Gottfried (SUI),238,1710,URS,NSK,3,2
195,1966,23 Jul 1966 - 15:00,Quarter-finals,Goodison Park,Liverpool,Portugal,5,3,Korea,,...,3,ASHKENAZI Menachem (ISR),GALBA Karol (TCH),SCHWINTE Pierre (FRA),239,1702,POR,NSK,8,5
364,1986,02 Jun 1986 - 12:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Argentina,3,1,Korea,,...,0,SANCHEZ ARMINIO Victoriano (ESP),GONZALEZ ROA Gabriel (PAR),DIAZ PALACIO Jesus (COL),308,395,ARG,KOR,4,2
421,1990,12 Jun 1990 - 17:00,Group E,Marc Antonio Bentegodi,Verona,Belgium,2,0,Korea,,...,0,MAURO Vincent (USA),SNODDY Alan (NIR),COURTNEY George (ENG),322,57,BEL,KOR,2,0
464,1994,17 Jun 1994 - 19:30,Group C,Cotton Bowl,Dallas,Spain,2,2,Korea,,...,0,MIKKELSEN Peter (DEN),CHRISTENSEN Carl-Johan Meyer (DEN),PEARSON Roy (ENG),337,3050,ESP,KOR,4,0
490,1994,27 Jun 1994 - 16:00,Group C,Cotton Bowl,Dallas,Germany,3,2,Korea,,...,0,QUINIOU Joel (FRA),IVANOV Valentin (RUS),HASSAN Abdel-Magid (EGY),337,3076,GER,KOR,5,3
542,1998,20 Jun 1998 - 21:00,Group E,Stade V�lodrome,Marseilles,Netherlands,5,0,Korea,,...,0,WOJCIK Ryszard (POL),POCIEGIEL Jacek (POL),DUPANOV Yuri (BLR),1014,8749,NED,KOR,5,2
556,1998,25 Jun 1998 - 16:00,Group E,Parc des Princes,Paris,Belgium,1,1,Korea,,...,0,REZENDE Marcio (BRA),PINTO Arnaldo (BRA),ARANGO Jorge Luis (COL),1014,8765,BEL,KOR,2,1
625,2002,14 Jun 2002 - 20:30,Group D,Incheon Football Stadium,Incheon,Portugal,0,1,Korea,,...,0,SANCHEZ Angel (ARG),ALTRAIFI Ali (KSA),SZEKELY Ferenc (HUN),43950100,43950047,POR,KOR,1,0
639,2002,22 Jun 2002 - 15:30,Quarter-finals,Gwangju World Cup Stadium,Gwangju,Spain,0,0,Korea,Korea Republic win on penalties (3 - 5),...,0,EL GHANDOUR Gamal (EGY),TOMUSANGE Ali (UGA),RAGOONATH Michael (TRI),43950300,43950059,ESP,KOR,0,0
640,2002,25 Jun 2002 - 20:30,Semi-finals,Seoul World Cup Stadium,Seoul,Germany,1,0,Korea,,...,0,MEIER Urs (SUI),ARNAULT Frederic (FRA),AMLER Evzen (CZE),43950400,43950061,GER,KOR,1,0
672,2006,18 Jun 2006 - 21:00,Group G,Zentralstadion,Leipzig,France,1,1,Korea,,...,0,ARCHUNDIA Benito (MEX),RAMIREZ Jose (MEX),VERGARA Hector (CAN),97410100,97410029,FRA,KOR,2,1
691,2006,23 Jun 2006 - 21:00,Group G,"FIFA World Cup Stadium, Hanover",Hanover,Switzerland,2,0,Korea,,...,0,ELIZONDO Horacio (ARG),GARCIA Dario (ARG),OTERO Rodolfo (ARG),97410100,97410046,SUI,KOR,2,1
721,2010,15 Jun 2010 - 20:30,Group G,Ellis Park Stadium,Johannesburg,Brazil,2,1,Korea,,...,0,KASSAI Viktor (HUN),EROS Gabor (HUN),VAMOS Tibor (HUN),249722,300061490,BRA,NSK,3,0
725,2010,17 Jun 2010 - 13:30,Group B,Soccer City Stadium,Johannesburg,Argentina,4,1,Korea,,...,1,DE BLEECKERE Frank (BEL),HERMANS Peter (BEL),VROMANS Walter (BEL),249722,300061458,ARG,KOR,5,3
737,2010,21 Jun 2010 - 13:30,Group G,Cape Town Stadium,Cape Town,Portugal,7,0,Korea,,...,0,POZO Pablo (CHI),BASUALTO Patricio (CHI),MONDRIA Francisco (CHI),249722,300061487,POR,NSK,7,1
742,2010,22 Jun 2010 - 20:30,Group B,Durban Stadium,Durban,Nigeria,2,2,Korea,,...,1,Oleg�rio BENQUEREN�A (POR),CARDINAL Jose (POR),MIRANDA Bertino (POR),249722,300111115,NGA,KOR,4,2
756,2010,26 Jun 2010 - 16:00,Round of 16,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Uruguay,2,1,Korea,,...,0,Wolfgang STARK (GER),SALVER Jan-Hendrik (GER),PICKEL Mike (GER),249717,300061504,URU,KOR,3,1
788,2014,17 Jun 2014 - 18:00,Group H,Arena Pantanal,Cuiaba,Russia,1,1,Korea,,...,0,PITANA Nestor (ARG),MAIDANA Hernan (ARG),BELATTI Juan Pablo (ARG),255931,300186499,RUS,KOR,2,0

## Summary

In this lab, you learned how to access data within Pandas!